---
ID: "77e59988-e198-47dd-bd60-04ee8e9efc8d"
Parent: "84379fc9-e395-470f-9d6b-ea4a2654ae86"
Template: "84379fc9-e395-470f-9d6b-ea4a2654ae86"
Path: /sitecore/templates/Sitecore Cognitive Services/Image Search/Image Analysis/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171228T184102Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
